Reschedule unprocessed tasks based on a cron and locking mechanism to avoid errors
lblod/besluit-publicatie-melding-service pull request #3
Opened 2021-06-30 10:39 UTC by lagartoverde

2021-06-30 10:45 UTC, lagartoverde commented
I think this is weird to review because it's not like I can 100% test what will happen, theoretically for me it seems good and I would want confirmation that the lock is placed correctly. 
I placed it there in order to avoid processing the tasks multiple times when the submit publication and the cronjob runs concurrently, the lock should avoid the concurrent execution.

2021-07-05 16:56 UTC, abeforgit commented
https://github.com/rogierschouten/async-lock/issues/43 not a very reassuring look for this library I gotta say

2021-07-05 19:16 UTC, abeforgit requested changes
Still havent tested the actual function
struggling with getting the stacks to work together as usual

2021-07-05 19:16 UTC, abeforgit commented on app.js
> +const CRON_FREQUENCY = process.env.RESCHEDULE_CRON_PATTERN || '0 0 * * *';
Would be nice if you could document the new env variable in the readme

2021-07-05 19:16 UTC, abeforgit commented on app.js
> +async function proccessUnasignedResources() {
small typo here
it should be "processUnassignedResources"

2021-07-05 19:16 UTC, abeforgit commented on app.js
> +async function proccessUnasignedResources() {
in general, what's the difference between this method and rescheduleUnprocessedTasks?
this one seems to call `getUnProcessedTasks`, which is weird since the name implies it handles unassigned resources?

2021-07-06 07:31 UTC, lagartoverde commented on app.js
> +async function proccessUnasignedResources() {
I was a little bit tired yesterday and my brain struggled to name things, I will try again hahahaha

2021-07-07 06:22 UTC, nvdk approved these changes
looks good to me, perhaps add that documentation for RESCHEDULE_CRON_PATTERN to the readme as arne suggested?

2021-07-07 08:28 UTC, merged